import { jsPDF } from 'jspdf'
import { SetlistItem, WaveformMarker, MARKER_TYPE_COLORS } from '../store'

interface CueSheetOptions {
  presetName: string
  setlist: SetlistItem[]
  markers: Record<string, WaveformMarker[]>
  fps: number
}

function formatTime(sec: number): string {
  const h = Math.floor(sec / 3600)
  const m = Math.floor((sec % 3600) / 60)
  const s = Math.floor(sec % 60)
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

export function exportCueSheetPdf(options: CueSheetOptions): Uint8Array {
  const { presetName, setlist, markers, fps } = options
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 15
  let y = 20

  const checkPage = (needed: number): void => {
    if (y + needed > 275) {
      doc.addPage()
      y = 20
    }
  }

  // Title
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(`LTCast Cue Sheet — ${presetName || 'Untitled'}`, margin, y)
  y += 8

  // Date
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120)
  doc.text(new Date().toLocaleDateString() + ' ' + new Date().toLocaleTimeString(), margin, y)
  doc.text(`${fps} fps`, pageW - margin, y, { align: 'right' })
  y += 8

  doc.setTextColor(0)

  if (setlist.length === 0) {
    doc.setFontSize(11)
    doc.text('No songs in setlist.', margin, y)
    return doc.output('arraybuffer') as unknown as Uint8Array
  }

  // Setlist table
  for (let i = 0; i < setlist.length; i++) {
    const song = setlist[i]
    const songName = song.name
    const songMarkers = markers[song.path] ?? []
    const songCues = song.midiCues ?? []
    const sortedMarkers = [...songMarkers].sort((a, b) => a.time - b.time)

    // Song header
    checkPage(16)
    doc.setFillColor(30, 30, 30)
    doc.rect(margin, y - 4, pageW - margin * 2, 8, 'F')
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(255)
    doc.text(`${i + 1}. ${songName}`, margin + 2, y + 1)
    if (song.notes) {
      doc.setFontSize(8)
      doc.setFont('helvetica', 'italic')
      doc.text(song.notes, pageW - margin - 2, y + 1, { align: 'right' })
    }
    doc.setTextColor(0)
    y += 10

    // Markers
    if (sortedMarkers.length > 0) {
      checkPage(8)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(80)
      doc.text('MARKERS', margin + 2, y)
      y += 5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      for (const m of sortedMarkers) {
        checkPage(5)
        doc.setTextColor(0)
        doc.text(formatTime(m.time), margin + 4, y)
        const typeLabel = m.type ? m.type.toUpperCase() : 'CUSTOM'
        const color = MARKER_TYPE_COLORS[m.type ?? 'custom']
        // Parse hex color
        const r = parseInt(color.slice(1, 3), 16)
        const g = parseInt(color.slice(3, 5), 16)
        const b = parseInt(color.slice(5, 7), 16)
        doc.setTextColor(r, g, b)
        doc.text(typeLabel, margin + 28, y)
        doc.setTextColor(60)
        doc.text(m.label || '', margin + 52, y)
        y += 4
      }
      y += 2
    }

    // MIDI Cues
    if (songCues.length > 0) {
      checkPage(8)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(80)
      doc.text('MIDI CUES', margin + 2, y)
      y += 5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      for (const cue of songCues) {
        if (!cue.enabled) continue
        checkPage(5)
        doc.setTextColor(0)
        doc.text(cue.triggerTimecode, margin + 4, y)
        doc.setTextColor(0, 150, 200)
        const msgType = cue.messageType === 'program-change' ? 'PC'
          : cue.messageType === 'note-on' ? 'NOTE'
          : 'CC'
        doc.text(`${msgType} ch${cue.channel} #${cue.data1}${cue.data2 !== undefined ? ` v${cue.data2}` : ''}`, margin + 35, y)
        doc.setTextColor(100)
        doc.text(cue.label || '', margin + 75, y)
        y += 4
      }
      y += 2
    }

    y += 4
  }

  // Footer
  doc.setFontSize(7)
  doc.setTextColor(150)
  doc.text('Generated by LTCast', margin, 290)

  return new Uint8Array(doc.output('arraybuffer'))
}
